### ISSUE TITLE
Unable to connect to server error

### ISSUE THREAD

**Issue by Error-418** [jaumeortola/languagetool-msword10-addin#10]
Running into an error when attempting to connect to my local server. Here's a dump from my PowerShell output from the server:

`PS C:\Program Files\LanguageTool-4.3> java -jar .\languagetool.jar
Setting up thread pool with 10 threads
Starting LanguageTool 4.3 (build date: 2018-09-26 12:13) server on http://localhost:8081...
Server started
Stopping server
Server stopped
Setting up thread pool with 10 threads
Starting LanguageTool 4.3 (build date: 2018-09-26 12:13) server on http://localhost:8081...
Server started
2018-10-01 16:58:35 An error has occurred: 'Seems like you're using an old version of our API that's not supported anymore. Please see https://languagetool.org/http-api/migration.php', sending HTTP code 400. Access from 127.0.0.1, HTTP user agent: null, User agent param: msword, Referrer: null, language: en-US, h: 1, r: 1, time: 3, text length: 186, Stacktrace follows:
java.lang.IllegalArgumentException: Seems like you're using an old version of our API that's not supported anymore. Please see https://languagetool.org/http-api/migration.php
        at org.languagetool.server.LanguageToolHttpHandler.handle(LanguageToolHttpHandler.java:155)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.AuthFilter.doFilter(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(Unknown Source)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Unknown Source)
        at sun.net.httpserver.ServerImpl$Exchange.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`

I've checked this across 4.1, 4.2, and 4.3. Strangely I'm not running into this on my home system, but I'm also using LanguageTool's free services at home. It's the stand-alone server that I'm encountering issues with.

Follow up (since I just solved my problem, and this should probably be added to the README). The user will need to set LanguageTool Server to `http://localhost:8081/v2/` if the trailing slash is missing, or the formatting is otherwise changed the above error message will be generated by the server. (This is probably bad praxis on LT's side, but I'm not going to tell them that...)

**Comment by jaumeortola** [comment]
Thanks for your comment. I have added this information to the README file.
